FROM python:3.11.2-slim-buster

WORKDIR /code

COPY ./requirements-test.txt /code/requirements-test.txt

RUN pip install --upgrade pip

RUN pip install -r  /code/requirements-test.txt 

COPY ./app /code/app

COPY ./tests /code/tests

CMD ["python","-m","pytest","--cov=app","tests"]